# Path to the base model
base_model: /home/NLP_CORE/HUB_LLM/Llama-3-8B-Instruct
model_type: AutoModelForCausalLM
tokenizer_type: AutoTokenizer
load_in_8bit: false
load_in_4bit: false
strict: false

datasets:
  - path: /workspace/home/LFew-TOD/data/share_gpt_format/dst-720-llama3.jsonl
    type: input_output
  - path: /workspace/home/LFew-TOD/data/share_gpt_format/dst-22-10percent-llama3.jsonl
    type: input_output
  - path: /workspace/home/LFew-TOD/data/share_gpt_format/e2e-22-10percent-llama3.jsonl
    type: input_output
            
val_set_size: 0.01
output_dir: /home/LFew-TOD/ckpt/lora-out-axolotl/

sequence_len: 4096 
sample_packing: false
pad_to_sequence_len: true

adapter: lora
lora_model_dir:
lora_r: 32 
lora_alpha: 16
lora_dropout: 0.05
lora_target_linear: false
lora_target_modules:
  - q_proj
  - v_proj
lora_fan_in_fan_out:
gradient_accumulation_steps: 2
micro_batch_size: 1
num_epochs: 4
optimizer: paged_adamw_32bit # adamw_torch 
lr_scheduler: cosine
learning_rate: 0.0003

train_on_inputs: false
group_by_length: false
bf16: auto
fp16: 
tf32: false
gradient_checkpointing: true
logging_steps: 1

warmup_steps: 100
evals_per_epoch: 10
eval_table_size:
eval_max_new_tokens: 128
saves_per_epoch: 1
weight_decay: 0.01
         
special_tokens:
    pad_token: <|end_of_text|>
    